### ISSUE TITLE
errror load dependency

### ISSUE THREAD

**Issue by webserveis** [bardss/PaintableVectorView#4]
No found library 
jcenter is deprecated

**Comment by bardss** [comment]
I will try to take care of it in following weeks. 
Thanks for pointing that out

**Comment by bardss** [comment]
Updated all the dependencies, gradle, Kotlin, and removed jcenter.
Try version 1.0.2 and tell me if this fixed your issue @webserveis

**Comment by webserveis** [comment]
Works fine, thanks
